### ISSUE TITLE
Add an option to use full file name instead of just base name

### ISSUE THREAD

**Issue by Andrew15-5** [rasulomaroff/cmp-bufname#2]
If I have a file `a.typ` it will only complete `a` and not `a.typ` which at least in some cases defeats the whole (-extension) purpose of file name autocompletion. Maybe list for both with and without file extension? This should of course be configurable.

P.S. I tried #1, but that plugin didn't work (with nvim v0.10.0).

**Comment by rasulomaroff** [comment]
Hi there! Agree, it makes sense to make this configurable

**Comment by rasulomaroff** [comment]
Hi there! Just added a configuration option that you can use, check README :)

**Comment by Andrew15-5** [comment]
Thanks. But I still get the file names without an extension as an unnecessary bonus when using `return { file_name }` (in addition to `file_name`).

**Comment by rasulomaroff** [comment]
Can you share your config please? Maybe it's coming not from this source at all

**Comment by rasulomaroff** [comment]
@Andrew15-5 Just checked that on my machine and it works fine. Probably another source that keeps putting it in your case.

**Comment by Andrew15-5** [comment]
When I disabled this plugin, the file name stopped showing.

Maybe later I can investigate further, I'm busy.
